In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [2]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0            vicariapastoralgdl.org        0        0           0          1   
1                           hamt.jp        0        0           1          7   
2  secure-account-info.openvcsme.cf        0        0           1          1   
3                   distractify.com        0        0           1         10   
4                      turkmcse.com        0        0           0          2   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  \
0            0             0        0              0           0            0   
1            0             0        0              0           0            1   
2            0             0        0              1           0            0   
3            0             0        0              0           0            1   
4            0             0        0              0           0            1   

   Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  \
0           1           1       0           0            1             0   
1           1           1       0           0            1             0   
2           1           1       0           0            1             0   
3           0           1       0           0            1             0   
4           0           0       0           0            1             0   

   Label  
0      1  
1      1  
2      1  
3      0  
4      1

In [3]:
X = data.drop(['Domain', 'Label'], axis=1)

In [4]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           0          1            0             0   
1        0        0           1          7            0             0   
2        0        0           1          1            0             0   
3        0        0           1         10            0             0   
4        0        0           0          2            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            0           1           1   
1        0              0           0            1           1           1   
2        0              1           0            0           1           1   
3        0              0           0            1           0           1   
4        0              0           0            1           0           0   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [5]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [7]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [9]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.802
Precision: 0.8277787979191181
Recall: 0.802
F1 Score: 0.7978846154020748
Confusion Matrix:
[[1420   86]
 [ 508  986]]

SVC Metrics:
Accuracy: 0.8293333333333334
Precision: 0.8650492551239878
Recall: 0.8293333333333334
F1 Score: 0.8249236326707328
Confusion Matrix:
[[1485   21]
 [ 491 1003]]

RandomForestClassifier Metrics:
Accuracy: 0.8676666666666667
Precision: 0.8751649657431135
Recall: 0.8676666666666667
F1 Score: 0.8669580054473078
Confusion Matrix:
[[1414   92]
 [ 305 1189]]

MLPClassifier Metrics:
Accuracy: 0.8443333333333334
Precision: 0.852610277637612
Recall: 0.8443333333333334
F1 Score: 0.8433560282345803
Confusion Matrix:
[[1388  118]
 [ 349 1145]]

KNeighborsClassifier Metrics:
Accuracy: 0.8066666666666666
Precision: 0.8075381144824342
Recall: 0.8066666666666666
F1 Score: 0.8065560264501352
Confusion Matrix:
[[1177  329]
 [ 251 1243]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8633333333333333
Precision: 0.8718520036952612
Reca

In [10]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.867667   0.875165  0.867667  0.866958
5  DecisionTreeClassifier  0.863333   0.871852  0.863333  0.862497
3           MLPClassifier  0.844333   0.852610  0.844333  0.843356
1                     SVC  0.829333   0.865049  0.829333  0.824924
4    KNeighborsClassifier  0.806667   0.807538  0.806667  0.806556
0      LogisticRegression  0.802000   0.827779  0.802000  0.797885
